### ISSUE TITLE
[Suggestion] Make vanilla Eyes of Ender usable in combination with custom eyes 

### ISSUE THREAD

**Issue by kristibektashi** [Team-Remastered/End-Remastered-Forge#45]
Instead of simply making them unable to be placed, instead we should have the ability to use a single vanilla eye of ender alongside 11 custom eyes to activate the end portal. If you try to place a second vanilla eye of ender when the first one is already placed (even if it's a naturally generated one) it should say that this eye is already placed, just like with custom eyes. There should be an option in the config. 

I understand the whole point of this mod is to use the custom eyes. But it doesn't make sense for me that the vanilla eyes don't work at all. I believe they should work just like the custom ones, with only one per portal. You would still need to fill the other frames with custom eyes.

**Comment by Jack-Bagel** [comment]
I already planned to make it so that the portal can still be opened if there's already an eye of ender in the portal frame. However, I don't plan on making the eye of ender usable.

**Comment by kristibektashi** [comment]
Perhaps it could be a config option that is disabled by default?

**Comment by Catomax262** [comment]
> I already planned to make it so that the portal can still be opened if there's already an eye of ender in the portal frame. However, I don't plan on making the eye of ender usable.

Honestly, i kind of see this as a spoil, imagine not remembering anything about this mod (in my case i have lots and lots of mods and i wanted to go to the end portal), and going to craft some ender eyes to find the stronghold, just to find that they're completely useless because of this mod's eyes. Also, ruins the surprise from vanilla minecraft that is finding some already placed eyes on the frame with enough luck. Basically this is counteractive due to rendering ender eyes' functionality to only work as recipe-only for other mods instead of the original purpose of showing you the way to the stronghold.

Honestly, i prefer having to find your way the stronghold **only** with Ender Eyes, but still having to search for the other eyes to fill up the frame and enter the End.
