### ISSUE TITLE
Eyes not working, stronghold and end gate/lost castle not generating

### ISSUE THREAD

**Issue by Disayed** [Team-Remastered/End-Remastered-Forge#56]
Both modded eyes and regular eyes are not working (nothing happens)
Unable to /locate either a regular stronghold or a lost castle (or end gate)
Unable to place any eyes in a man-made portal

This is on 
forge 47.1.3
E-R 5.2.3 R 1.20.X
TLC forge 1.0.3 R 1.20.X
I use Terralith as world generator modifier, either with or without issues are the same

here is the list of mods presents in my folder : 

![image](https://github.com/Team-Remastered/End-Remastered-Forge/assets/141853223/2afe8781-68f1-42c6-98e0-108ba9c7f560)

I am available for any additional informations.

**Comment by Jack-Bagel** [comment]
Any mod that could cause this issue in your opinion? The stronghold is not supposed to spawn when The lost castle is installed so that's normal, but you should be able to /locate the castle. As for End Remastered, make sure the portal is built correctly with the frames looking in the right direction.

**Comment by Disayed** [comment]
Well it seems like it was my bad the whole time, I have a config file named stronghold 1.18.2 which is completely empty (I am running 1.20.1)

Just checked with a new world, having deleted this and everything works fine

Thank you for the good content!
